"""Firewall policy details tool with resolved names.

Provides a single read-only tool that returns firewall policies with all
raw IDs (zones, networks, IP groups, port groups) resolved to human-readable
names. Supports fetching all custom policies, a single policy by ID, or
searching by name.
"""

from typing import Any

from fastmcp.server.providers import LocalProvider

from ..api.pool import get_network_client
from ..config import APIType, Settings
from ..models.firewall_policy import FirewallPolicy
from ..utils import get_logger

logger = get_logger(__name__)
provider = LocalProvider()

__all__ = [
    "provider",
    "get_firewall_policy_details",
]

# Generic system policy names that are auto-generated by UniFi.
# These are filtered out when listing all policies (but not when
# fetching a specific policy_id).
_SYSTEM_POLICY_NAMES = frozenset(
    {
        "Allow All Traffic",
        "Block All Traffic",
        "Block Invalid Traffic",
        "Allow Return Traffic",
        "Allow DNS",
        "Allow ICMP",
        "Allow DHCP",
        "Allow ICMPv6",
        "Allow DHCPv6",
        "Allow Neighbor Solicitations",
        "Allow Neighbor Advertisements",
        "Allow IPsec",
        "Allow ESP",
        "Allow Public DNS",
        "Post-Authorization Restrictions",
        "Allow Hotspot Portal",
        "Allow mDNS",
    }
)


def _ensure_local_api(settings: Settings) -> None:
    if settings.api_type != APIType.LOCAL:
        raise NotImplementedError(
            "Firewall policy details (v2 API) are only available when "
            "UNIFI_API_TYPE='local'. Configure a local UniFi gateway connection."
        )


def _is_system_policy(name: str) -> bool:
    """Check if a policy name is a generic system default or auto-generated return rule."""
    return name in _SYSTEM_POLICY_NAMES or name.endswith("(Return)")


async def _build_lookup_maps(
    client: Any,
    site_name: str,
    site_uuid: str,
) -> tuple[dict[str, str], dict[str, str], dict[str, dict[str, Any]]]:
    """Fetch zones, networks, and firewall groups to build ID→name maps.

    Returns:
        (zone_map, network_map, group_map) where:
        - zone_map: zone_id → zone name
        - network_map: network_id → network name (both Integration and legacy IDs)
        - group_map: group_id → {"name": str, "type": str, "members": list[str]}
    """
    # Fetch all three in sequence (same client, can't truly parallel without asyncio.gather
    # on separate coroutines, but these are fast local calls)
    import asyncio

    zones_coro = client.get(client.integration_path(site_uuid, "firewall/zones"))
    networks_coro = client.get(client.integration_path(site_uuid, "networks"))
    legacy_networks_coro = client.get(client.legacy_path(site_name, "rest/networkconf"))
    groups_coro = client.get(client.legacy_path(site_name, "rest/firewallgroup"))

    zones_raw, networks_raw, legacy_networks_raw, groups_raw = await asyncio.gather(
        zones_coro, networks_coro, legacy_networks_coro, groups_coro
    )

    # Zone map — Integration API zones (UUID format)
    zones = zones_raw if isinstance(zones_raw, list) else zones_raw.get("data", [])
    zone_map: dict[str, str] = {}
    # Build integration_zone_id → name
    integration_zone_names: dict[str, str] = {}
    # Build integration_zone_id → set of integration_network_ids
    integration_zone_networks: dict[str, set[str]] = {}
    for z in zones:
        zid = z.get("id", "")
        zname = z.get("name", zid)
        if zid:
            zone_map[zid] = zname
            integration_zone_names[zid] = zname
            integration_zone_networks[zid] = set(z.get("networkIds", []))

    # Network map (Integration API uses "id", legacy uses "_id")
    network_map: dict[str, str] = {}
    networks = networks_raw if isinstance(networks_raw, list) else networks_raw.get("data", [])
    # Also build integration_network_id → integration_zone_id from zoneId field
    integration_net_to_zone: dict[str, str] = {}
    for n in networks:
        nid = n.get("id", "")
        nname = n.get("name", nid)
        if nid:
            network_map[nid] = nname
            iz = n.get("zoneId", "")
            if iz:
                integration_net_to_zone[nid] = iz

    legacy_networks = (
        legacy_networks_raw
        if isinstance(legacy_networks_raw, list)
        else legacy_networks_raw.get("data", [])
    )
    # Build v2_zone_id → zone_name by cross-referencing legacy networks
    # (which have firewall_zone_id in v2 format) with Integration networks
    # (which have zoneId in Integration format → zone name).
    # Match by network name since both APIs use the same names.
    legacy_name_to_integration_zone: dict[str, str] = {}
    for n in networks:
        nname = n.get("name", "")
        iz = n.get("zoneId", "")
        if nname and iz and iz in integration_zone_names:
            legacy_name_to_integration_zone[nname] = integration_zone_names[iz]

    for n in legacy_networks:
        nid = n.get("_id", "")
        nname = n.get("name", nid)
        if nid:
            network_map[nid] = nname
        # Map v2 zone IDs to zone names via network name cross-reference
        v2_zone_id = n.get("firewall_zone_id", "")
        if v2_zone_id and v2_zone_id not in zone_map and nname in legacy_name_to_integration_zone:
            zone_map[v2_zone_id] = legacy_name_to_integration_zone[nname]

    # Group map
    groups_list = groups_raw if isinstance(groups_raw, list) else groups_raw.get("data", [])
    group_map: dict[str, dict[str, Any]] = {}
    for g in groups_list:
        gid = g.get("_id", "")
        if gid:
            group_map[gid] = {
                "name": g.get("name", gid),
                "type": g.get("group_type", "unknown"),
                "members": g.get("group_members", []),
            }

    return zone_map, network_map, group_map


def _resolve_match_target(
    target: dict[str, Any],
    zone_map: dict[str, str],
    network_map: dict[str, str],
    group_map: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Resolve a source or destination match target, enriching IDs with names."""
    resolved: dict[str, Any] = {}

    # Zone
    zone_id = target.get("zone_id", "")
    resolved["zone_id"] = zone_id
    resolved["zone_name"] = zone_map.get(zone_id, zone_id)

    # Matching target type
    resolved["matching_target"] = target.get("matching_target", "ANY")

    # Networks
    network_ids = target.get("network_ids") or []
    if network_ids:
        resolved["network_ids"] = network_ids
        resolved["network_names"] = [network_map.get(nid, nid) for nid in network_ids]

    # IPs
    ips = target.get("ips")
    if ips:
        resolved["ips"] = ips

    # Client MACs
    client_macs = target.get("client_macs")
    if client_macs:
        resolved["client_macs"] = client_macs

    # Ports
    port = target.get("port")
    port_matching = target.get("port_matching_type", "ANY")
    if port_matching != "ANY" and port:
        resolved["port"] = port

    # IP group
    ip_group_id = target.get("ip_group_id")
    if ip_group_id:
        group_info = group_map.get(
            ip_group_id, {"name": ip_group_id, "type": "unknown", "members": []}
        )
        resolved["ip_group"] = {
            "id": ip_group_id,
            "name": group_info["name"],
            "members": group_info["members"],
        }

    # Port group
    port_group_id = target.get("port_group_id")
    if port_group_id:
        group_info = group_map.get(
            port_group_id, {"name": port_group_id, "type": "unknown", "members": []}
        )
        resolved["port_group"] = {
            "id": port_group_id,
            "name": group_info["name"],
            "members": group_info["members"],
        }

    return resolved


def _resolve_policy(
    policy: dict[str, Any],
    zone_map: dict[str, str],
    network_map: dict[str, str],
    group_map: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Resolve a single firewall policy, enriching all IDs with names."""
    return {
        "id": policy.get("id", policy.get("_id", "")),
        "name": policy.get("name", ""),
        "action": policy.get("action", ""),
        "enabled": policy.get("enabled", True),
        "protocol": policy.get("protocol", "all"),
        "ip_version": policy.get("ip_version", "BOTH"),
        "index": policy.get("index", 10000),
        "description": policy.get("description", ""),
        "create_allow_respond": policy.get("create_allow_respond", False),
        "source": _resolve_match_target(policy.get("source", {}), zone_map, network_map, group_map),
        "destination": _resolve_match_target(
            policy.get("destination", {}), zone_map, network_map, group_map
        ),
    }


@provider.tool()
async def get_firewall_policy_details(
    site_id: str,
    policy_id: str | None = None,
    search: str | None = None,
) -> dict[str, Any]:
    """Get firewall policies with all IDs resolved to human-readable names.

    Returns policies with zone names, network names, IP/port group contents,
    and client MACs resolved inline. Filters out system-default policies
    unless a specific policy_id is requested.

    Args:
        site_id: Site identifier (e.g., 'default')
        policy_id: Get a single policy by ID with full resolved details
        search: Filter policies by name (case-insensitive substring match)

    Returns:
        Dictionary with 'policies' (list of resolved policies), 'zones',
        'groups', and 'total' count.
    """
    client = get_network_client()
    _ensure_local_api(client.settings)

    if not client.is_authenticated:
        await client.authenticate()

    site = await client.resolve_site(site_id)

    # Build lookup maps
    zone_map, network_map, group_map = await _build_lookup_maps(client, site.name, site.uuid)

    # Fetch policies
    if policy_id:
        endpoint = client.v2_path(site.name, f"firewall-policies/{policy_id}")
        response = await client.get(endpoint)
        data = response.get("data", response) if isinstance(response, dict) else response
        raw_policies = [data] if isinstance(data, dict) else [data]
    else:
        endpoint = client.v2_path(site.name, "firewall-policies")
        response = await client.get(endpoint)
        raw_policies = response if isinstance(response, list) else response.get("data", [])

    # Parse through Pydantic model to normalize field names (_id → id)
    policies = []
    for raw in raw_policies:
        parsed = FirewallPolicy(**raw).model_dump()
        policies.append(parsed)

    # Filter: skip system defaults unless specific policy_id requested
    if not policy_id:
        policies = [p for p in policies if not _is_system_policy(p.get("name", ""))]

    # Filter: search by name
    if search:
        search_lower = search.lower()
        policies = [p for p in policies if search_lower in p.get("name", "").lower()]

    # Resolve all policies
    resolved = [_resolve_policy(p, zone_map, network_map, group_map) for p in policies]

    # Build zones and groups summary for context
    zones_summary = [{"id": zid, "name": zname} for zid, zname in zone_map.items()]
    groups_summary = [
        {"id": gid, "name": ginfo["name"], "type": ginfo["type"], "members": ginfo["members"]}
        for gid, ginfo in group_map.items()
    ]

    logger.info(
        f"Retrieved {len(resolved)} firewall policy details for site '{site_id}'"
        + (f" (search='{search}')" if search else "")
        + (f" (policy_id='{policy_id}')" if policy_id else "")
    )

    return {
        "total": len(resolved),
        "policies": resolved,
        "zones": zones_summary,
        "groups": groups_summary,
    }
